### PR TITLE
Move brewed files to libexec subfolder

### PR DESCRIPTION
**Pull request by Bl4Cc4t**

### CODE REVIEW

**Comment by Difegue** [comment]
(continuing the conversation from https://github.com/Bl4Cc4t/homebrew-other/commit/164b9c1c1d17dcf082e8ac794be7aec3880c1d7f )
One of the reasons I wanted to avoid extra repo changes was to not have to wait for yet another release, yeah. 😅  
I can add those env var changes as-is and then merge to master and put out a `0.6.9-homebrew` tag. It won't be a full release, but it should give you something stable enough to base the formula on.

**Comment by Difegue** [comment]
Oh, didn't saw your edited comment back in the other commit. Sounds even better to me! 😁  
Although I still need to make a tag for this commit.

**Comment by Bl4Cc4t** [comment]
Well, we need a downloadable tarball to be accepted on core.
Is a small subsubsubrelease that bad? :/

**Comment by Difegue** [comment]
Well, tags can be downloaded as tarballs without any problem.  
Thing is, there seemingly isn't a way to have a tag without a release in GitHub, so I guess I'll have to make one. 😐

**Comment by Difegue** [comment]
[There ya go.](https://github.com/Difegue/LANraragi/archive/v.0.6.9-homebrew.tar.gz)

**Comment by Bl4Cc4t** [comment]
https://github.com/Bl4Cc4t/homebrew-other/commit/5c9e57c6f599409ac41185224c156f325be25199
Wanna test it one final time?

**Comment by Difegue** [comment]
Gave it a quick shot on another VM, getting syntax errors in the formula it seems:  
image

**Comment by Bl4Cc4t** [comment]
These are merge markers, I wonder why they display? I do not get that error...

**Comment by Difegue** [comment]
Yeah, I was a bit tired yesterday when I tested this it seems 😅 Homebrew uses git internally when you `brew tap`, so I guess a merge conflict happened at some point because I modified the formula manually to test something.  

Cleared the tap and it's all good!  
image

**Comment by Bl4Cc4t** [comment]
created a PR: https://github.com/Homebrew/homebrew-core/pull/51869

**Pull request merged**
