### PR TITLE
Add Pixiv metadata plugin

### PR DESCRIPTION
**Pull request by psilabs-dev**
Adds Pixiv cookie login and metadata extraction for illustrations from pixiv.net.

## usage
Supported one-shot parameter format (can extract $illust_id for metadata extraction):
- simple ID extraction:`$illust_id`
- URL-based extraction: `pixiv.net/en/artworks/$illust_id`

Supported archive file format:
- `{$illust_id} title_of_work`
- `pixiv_{$illust_id} title_of_work`

## parameters
- `tag_languages`: include comma-separated list of strings for languages to extract (e.g. "en", "jp"). By default, an empty string parameter corresponds to extraction of untranslated tags, i.e. "jp" tags.

## metadata
A generic Pixiv illustration includes the following extractable metadata:
- `tags: list[str]`: list of comma-delimited strings for tags.
- `source: str`: URL link to Pixiv artwork
- `pixiv_user_id: int`: artist ID on pixiv (can be used to find user channel: `https://pixiv.net/en/users/$user_id`
- `artist: str`: name of artist/username
- `date_created: int`: epoch time of artwork creation in seconds
- `date_uploaded: int`: epoch time of upload in seconds

If the illustration is a *manga*, this plugin may include additional manga metadata:
- `pixiv_series_id: int`: ID of the series which this manga belongs to.
- `pixiv_series_title: str`: name of the manga series
- `pixiv_series_order: int`: position of this illustration within the manga series

--- 

Taggable strings (e.g. tags, artist, series title) are sanitized of special characters by the following logic:
- underscores are replaced by a space (e.g. "lorem_ipsum" -> "lorem ipsum")
- dashes preceded by space are removed (e.g. "lorem -ipsum" -> "lorem ipsum"; "lorem-ipsum" -> "lorem-ipsum")
- other special characters (`["?*%$:]`) are removed (e.g. "lorem: ipsum" -> "lorem ipsum")

### CODE REVIEW

**Comment by psilabs-dev** [comment]
For some of the fields, (e.g. user_id, series_id), this is exclusively a pixiv property, but different sources might also have their own user_id field which might result in possible metadata conflict. I'm thinking there are few ways to resolve this, which one is better?
- first way: make category specific to pixiv: `pixiv_user_id: 123456`.
- second way: making the id point to pixiv: `user_id: https://www.pixiv.net/users/123456`.

**Comment by Difegue** [comment]
A pixiv-specific namespace sounds like the way to go to me.

**Comment by Difegue** [comment]
👋 Apologies for the long time reviewing this; Stuff's been busy!  

On top of it, well, I don't have much to say at all... this looks perfect. 😤  
Who the hell goes this hard for a first-time contribution? Thanks a lot, I am humbled. 🙇

**Review by Difegue — APPROVED** [review]

**Comment by psilabs-dev** [comment]
Thanks👌 Development was easy thanks to seeing/copying the previous plugins haha, I just cleaned it up a bit. Love the project!

**Pull request merged**
