### PR TITLE
添加GA验证，汉化主要内容，分离用户和管理员，增加评论系统

### PR DESCRIPTION
**Pull request by oniyakun**
针对中国用户做了一些功能和使用性上的优化

For Chinese users did some functions and usability optimization.

Add GA Auth, localization the main pages and functions, separate users and administrators, add comment system.

Notice: Some features might be ONLY works for me.

### CODE REVIEW

**Comment by Difegue** [comment]
Thank you very much ! I'll need to rework the code a bit to work with multi-language and such, but I'll try to integrate the chinese translation when I'll be able to. 🙂👍

**Comment by oniyakun** [comment]
Maybe a new branch(⁎˃ᆺ˂)

**Comment by Difegue** [comment]
Yeah, that'd be better. 😀

**Comment by Difegue** [comment]
Put the work into a dedicated branch for now -- I'll get to it when time allows. Thanks again!

**Comment by oniyakun** [comment]
Holy... It means this is the first merged commit of my whole life, so surprised (˃ᆺ˂)

**Pull request merged**
